services:
  # service name that we will be able to use to refer to instead of localhost
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    # mapped volume on local machine (where data will be stored) to a volume in a container
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    # port mapping localhostmachine:container
    ports:
      - "5432:5432"
    # Add container name so that Docker doesn't add current folder prefix to service name
    container_name: pgdatabase
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    container_name: pgadmin
    